title = "宇宙戦争"
description = """
貴方は宇宙戦争のパイロットです。
敵の爆撃から街を守り、最終兵器エハラタワーを完成させましょう
左右キーで移動
zで弾丸発射
xで取り壊し
取り壊しは自分の真下のタイルを破壊することで一定時間無敵になれます
街はそれぞれ以下の効果を持っています
空き地-無
森林-無
町-無
都市-エハラタワーを完成させる為の住人を召喚
迫撃砲-副砲の強化
工場-連射力上昇
研究所-主砲強化
アンテナ-移動力上昇"""
author = "たかば"
game_exe_name = "hsptmp"
